version: "3.7"

services:
    app:
        build: .
        container_name: chatterbut-fastapi
        command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
        ports:
            - "80:80"
        volumes:
        # using bind mount to connect current folder into volume
            - .:/app
